baseURL = "http://example.org/"
languageCode = 'zh-cn'
title = "my blog Site"                #网站标题
enableRobotsTXT = true
enableEmoji = true
theme = "hinode"
[[module.imports]]
    path = 'github.com/gethinode/hinode'
