baseURL = "http://example.org/"
languageCode = 'zh-cn'
title = "Hello Finance"
enableRobotsTXT = true
enableEmoji = true
theme = "hinode"
[module]
[[module.imports]]
    path = 'github.com/gethinode/hinode'
